/**
 * Server-side PDF Generator for Evidence Bundles
 * Uses pdf-lib for deterministic, server-side PDF generation
 */

import { PDFDocument, rgb, StandardFonts, degrees } from 'pdf-lib'
import { createHash } from 'crypto'

export interface CaseData {
  id: string
  title: string
  description: string
  status: string
  created_at: string
  updated_at: string
  metadata?: Record<string, any>
}

export interface PDFGenerationOptions {
  timestamp: string
  generatedBy: string
  includeSignature: boolean
  watermark?: string
}

/**
 * Generate a deterministic PDF from case data
 * Same input will always produce the same output
 */
export async function generateEvidencePDF(
  caseData: CaseData,
  options: PDFGenerationOptions
): Promise<Buffer> {
  // Create a new PDF document
  const pdfDoc = await PDFDocument.create()

  // Embed standard fonts
  const titleFont = await pdfDoc.embedFont(StandardFonts.HelveticaBold)
  const bodyFont = await pdfDoc.embedFont(StandardFonts.Helvetica)
  const monoFont = await pdfDoc.embedFont(StandardFonts.Courier)

  // Add metadata
  pdfDoc.setTitle(`Evidence Bundle - ${caseData.title}`)
  pdfDoc.setAuthor(options.generatedBy)
  pdfDoc.setSubject('Anti-Black Racism Case Evidence')
  pdfDoc.setCreator('ABR Insights Platform')
  pdfDoc.setProducer('ABR Insights Evidence Generator v1.0')
  pdfDoc.setCreationDate(new Date(options.timestamp))
  pdfDoc.setModificationDate(new Date(options.timestamp))

  // Add first page
  const page = pdfDoc.addPage([612, 792]) // US Letter size
  const { width, height } = page.getSize()

  let yPosition = height - 50

  // Watermark if requested
  if (options.watermark) {
    page.drawText(options.watermark, {
      x: width / 2 - 150,
      y: height / 2,
      size: 72,
      font: titleFont,
      color: rgb(0.9, 0.9, 0.9),
      opacity: 0.3,
      rotate: degrees(-45),
    })
  }

  // Title
  page.drawText('EVIDENCE BUNDLE', {
    x: 50,
    y: yPosition,
    size: 24,
    font: titleFont,
    color: rgb(0, 0, 0),
  })
  yPosition -= 40

  // Case Title
  page.drawText(caseData.title, {
    x: 50,
    y: yPosition,
    size: 18,
    font: titleFont,
    color: rgb(0.2, 0.2, 0.2),
  })
  yPosition -= 30

  // Horizontal line
  page.drawLine({
    start: { x: 50, y: yPosition },
    end: { x: width - 50, y: yPosition },
    thickness: 2,
    color: rgb(0.8, 0.8, 0.8),
  })
  yPosition -= 30

  // Case Details
  const details = [
    { label: 'Case ID:', value: caseData.id },
    { label: 'Status:', value: caseData.status },
    { label: 'Created:', value: new Date(caseData.created_at).toLocaleString() },
    { label: 'Updated:', value: new Date(caseData.updated_at).toLocaleString() },
    { label: 'Generated:', value: new Date(options.timestamp).toLocaleString() },
    { label: 'Generated By:', value: options.generatedBy },
  ]

  for (const detail of details) {
    page.drawText(detail.label, {
      x: 50,
      y: yPosition,
      size: 10,
      font: titleFont,
      color: rgb(0.3, 0.3, 0.3),
    })
    page.drawText(detail.value, {
      x: 170,
      y: yPosition,
      size: 10,
      font: bodyFont,
      color: rgb(0, 0, 0),
    })
    yPosition -= 20
  }

  yPosition -= 20

  // Description Section
  page.drawText('DESCRIPTION', {
    x: 50,
    y: yPosition,
    size: 14,
    font: titleFont,
    color: rgb(0, 0, 0),
  })
  yPosition -= 25

  // Word wrap description
  const maxWidth = width - 100
  const words = caseData.description.split(' ')
  let line = ''

  for (const word of words) {
    const testLine = line + word + ' '
    const testWidth = bodyFont.widthOfTextAtSize(testLine, 11)

    if (testWidth > maxWidth && line.length > 0) {
      page.drawText(line, {
        x: 50,
        y: yPosition,
        size: 11,
        font: bodyFont,
        color: rgb(0, 0, 0),
      })
      yPosition -= 18
      line = word + ' '

      // Add new page if needed
      if (yPosition < 100) {
        const newPage = pdfDoc.addPage([612, 792])
        yPosition = height - 50
      }
    } else {
      line = testLine
    }
  }

  if (line.length > 0) {
    page.drawText(line, {
      x: 50,
      y: yPosition,
      size: 11,
      font: bodyFont,
      color: rgb(0, 0, 0),
    })
    yPosition -= 30
  }

  // Footer with signature
  if (options.includeSignature) {
    const footerY = 50
    page.drawText('OFFICIAL COPY - DO NOT REDISTRIBUTE', {
      x: 50,
      y: footerY,
      size: 8,
      font: monoFont,
      color: rgb(0.5, 0.5, 0.5),
    })

    page.drawText(
      `Document generated by ABR Insights Platform at ${new Date(options.timestamp).toISOString()}`,
      {
        x: 50,
        y: footerY - 15,
        size: 7,
        font: monoFont,
        color: rgb(0.6, 0.6, 0.6),
      }
    )
  }

  // Save PDF to buffer
  const pdfBytes = await pdfDoc.save()
  return Buffer.from(pdfBytes)
}

/**
 * Calculate SHA-256 checksum for integrity verification
 */
export function calculateChecksum(buffer: Buffer): string {
  return createHash('sha256').update(buffer).digest('hex')
}

/**
 * Generate file name for evidence bundle
 */
export function generateFileName(caseId: string, timestamp: Date): string {
  const dateStr = timestamp.toISOString().split('T')[0]
  const timeStr = timestamp.getTime()
  return `evidence-${caseId}-${dateStr}-${timeStr}.pdf`
}
