/**
 * AI Disclaimer Component (P1 Liability Protection)
 *
 * Prominently displays AI safety disclaimers and usage guidelines
 * Required for legal compliance and user awareness
 *
 * Features:
 * - Clear warning about AI limitations
 * - Report inappropriate content button
 * - Can be dismissed but persists across sessions
 */

'use client'

import { useState, useEffect } from 'react'
import { AlertTriangle, X, Flag } from 'lucide-react'
import { Alert, AlertDescription, AlertTitle } from '@/components/ui/alert'
import { Button } from '@/components/ui/button'

interface AIDisclaimerProps {
  variant?: 'chat' | 'coach' | 'default'
  persistenceKey?: string
  showReportButton?: boolean
  onReport?: () => void
  className?: string
}

export function AIDisclaimer({
  variant = 'default',
  persistenceKey = 'ai-disclaimer-dismissed',
  showReportButton = true,
  onReport,
  className = '',
}: AIDisclaimerProps) {
  const [dismissed, setDismissed] = useState(false)

  useEffect(() => {
    // Check if user has dismissed this disclaimer before
    const isDismissed = localStorage.getItem(persistenceKey) === 'true'
    setDismissed(isDismissed)
  }, [persistenceKey])

  const handleDismiss = () => {
    localStorage.setItem(persistenceKey, 'true')
    setDismissed(true)
  }

  const handleReport = () => {
    if (onReport) {
      onReport()
    } else {
      // Default: Navigate to support with AI report context
      window.location.href = '/support?type=ai-report'
    }
  }

  if (dismissed) {
    return null
  }

  const getContent = () => {
    switch (variant) {
      case 'chat':
        return {
          title: 'AI Assistant Disclaimer',
          description:
            'This AI assistant provides information based on trained data but may occasionally generate incorrect or incomplete responses. Always verify critical information with authoritative sources. Do not rely on AI responses for legal, medical, or professional advice.',
        }
      case 'coach':
        return {
          title: 'AI Coach Disclaimer',
          description:
            'AI coaching suggestions are generated based on patterns and may not address your specific situation. While helpful for general guidance, coaching sessions should complement—not replace—professional advice from qualified instructors or mentors. Always exercise critical judgment.',
        }
      default:
        return {
          title: 'AI-Generated Content Notice',
          description:
            'This content is generated by AI and may contain errors or inaccuracies. AI systems can sometimes produce biased, incomplete, or factually incorrect information. Please verify important details independently and report any concerning content.',
        }
    }
  }

  const { title, description } = getContent()

  return (
    <Alert
      variant="default"
      className={`border border-amber-500 bg-amber-50 dark:bg-amber-950/20${className}`}
    >
      <div className="flex items-start gap-3">
        <AlertTriangle className="mt-0.5 h-5 w-5 text-amber-600 dark:text-amber-500" />
        <div className="flex-1 space-y-2">
          <AlertTitle className="font-semibold text-amber-900 dark:text-amber-100">
            {title}
          </AlertTitle>
          <AlertDescription className="text-sm leading-relaxed text-amber-800 dark:text-amber-200">
            {description}
          </AlertDescription>
          {showReportButton && (
            <div className="flex gap-2 pt-1">
              <Button
                variant="outline"
                onClick={handleReport}
                className="gap-1.5 border border-amber-300 px-3 py-1.5 text-sm text-amber-700 hover:bg-amber-100 dark:border-amber-700 dark:text-amber-300 dark:hover:bg-amber-900/30"
              >
                <Flag className="h-3.5 w-3.5" />
                Report This Output
              </Button>
            </div>
          )}
        </div>
        <Button
          variant="ghost"
          onClick={handleDismiss}
          className="h-6 w-6 p-0 text-amber-700 hover:bg-amber-100 dark:text-amber-300 dark:hover:bg-amber-900/30"
          aria-label="Dismiss disclaimer"
        >
          <X className="h-4 w-4" />
        </Button>
      </div>
    </Alert>
  )
}

/**
 * Inline AI Badge - Subtle indicator for AI-generated content
 * Use this for smaller contexts where full disclaimer isn't appropriate
 */
export function AIBadge({ className = '' }: { className?: string }) {
  return (
    <span
      className={`inline-flex items-center gap-1 rounded bg-purple-100 px-2 py-0.5 text-xs font-medium text-purple-700 dark:bg-purple-950/30 dark:text-purple-300${className}`}
      title="AI-generated content"
    >
      <span className="relative flex h-2 w-2">
        <span className="absolute inline-flex h-full w-full animate-ping rounded-full bg-purple-400 opacity-75"></span>
        <span className="relative inline-flex h-2 w-2 rounded-full bg-purple-500"></span>
      </span>
      AI
    </span>
  )
}

/**
 * Persistent AI Warning Bar - Always visible reminder
 * Use this for critical pages where disclaimer must remain visible
 */
export function AIWarningBar({ className = '' }: { className?: string }) {
  return (
    <div
      className={`sticky top-0 z-40 border-b border-amber-200 bg-amber-500/10 backdrop-blur supports-[backdrop-filter]:bg-amber-500/5 dark:border-amber-800${className}`}
    >
      <div className="container flex items-center justify-center gap-2 py-2 text-sm">
        <AlertTriangle className="h-4 w-4 text-amber-600 dark:text-amber-400" />
        <span className="font-medium text-amber-900 dark:text-amber-100">AI-Assisted Feature</span>
        <span className="text-amber-700 dark:text-amber-300">
          Verify important information independently
        </span>
      </div>
    </div>
  )
}
