/**
 * Create RBAC Test Auth Users
 * 
 * Creates auth.users for the 9 test profiles using Supabase Admin API
 * This is safer than direct SQL insertion into auth schema
 */

import { createClient } from '@supabase/supabase-js';

const supabaseUrl = process.env.NEXT_PUBLIC_SUPABASE_URL!;
const serviceKey = process.env.SUPABASE_SERVICE_ROLE_KEY!;

const supabase = createClient(supabaseUrl, serviceKey);

const TEST_ACCOUNTS = [
  {
    id: '00000000-0000-0000-0000-000000000001',
    email: 'super_admin@abr-insights.com',
    password: 'TestPass123!',
    role: 'super_admin'
  },
  {
    id: '00000000-0000-0000-0000-000000000002',
    email: 'compliance@abr-insights.com',
    password: 'TestPass123!',
    role: 'compliance_officer'
  },
  {
    id: '00000000-0000-0000-0000-000000000003',
    email: 'orgadmin@abr-insights.com',
    password: 'TestPass123!',
    role: 'org_admin'
  },
  {
    id: '00000000-0000-0000-0000-000000000004',
    email: 'analyst@abr-insights.com',
    password: 'TestPass123!',
    role: 'analyst'
  },
  {
    id: '00000000-0000-0000-0000-000000000005',
    email: 'investigator@abr-insights.com',
    password: 'TestPass123!',
    role: 'investigator'
  },
  {
    id: '00000000-0000-0000-0000-000000000006',
    email: 'educator@abr-insights.com',
    password: 'TestPass123!',
    role: 'educator'
  },
  {
    id: '00000000-0000-0000-0000-000000000007',
    email: 'learner@abr-insights.com',
    password: 'TestPass123!',
    role: 'learner'
  },
  {
    id: '00000000-0000-0000-0000-000000000008',
    email: 'viewer@abr-insights.com',
    password: 'TestPass123!',
    role: 'viewer'
  },
  {
    id: '00000000-0000-0000-0000-000000000009',
    email: 'guest@abr-insights.com',
    password: 'TestPass123!',
    role: 'guest'
  }
];

async function createTestAuthUsers() {
  console.log('🔐 Creating RBAC Test Auth Users...\n');

  let created = 0;
  let skipped = 0;
  let errors = 0;

  for (const account of TEST_ACCOUNTS) {
    try {
      // Try to create user with specific UUID
      const { data, error } = await supabase.auth.admin.createUser({
        email: account.email,
        password: account.password,
        email_confirm: true,
        user_metadata: {
          role: account.role
        }
      });

      if (error) {
        if (error.message.includes('already') || error.message.includes('exists')) {
          console.log(`⏭️  ${account.email} - Already exists`);
          skipped++;
        } else {
          console.log(`❌ ${account.email} - ${error.message}`);
          errors++;
        }
      } else {
        console.log(`✅ ${account.email} - Created (${account.role})`);
        created++;

        // Note: The user UUID will be auto-generated by Supabase
        // We need to update the profile to use this new UUID
        if (data.user) {
          const { error: updateError } = await supabase
            .from('profiles')
            .update({ id: data.user.id })
            .eq('email', account.email);

          if (updateError) {
            console.log(`   ⚠️  Warning: Could not link profile (${updateError.message})`);
          }
        }
      }
    } catch (err: any) {
      console.log(`❌ ${account.email} - ${err.message}`);
      errors++;
    }
  }

  console.log('\n' + '='.repeat(60));
  console.log('📋 SUMMARY');
  console.log('='.repeat(60));
  console.log(`✅ Created: ${created}`);
  console.log(`⏭️  Skipped: ${skipped}`);
  console.log(`❌ Errors: ${errors}`);
  console.log(`📊 Total: ${TEST_ACCOUNTS.length}`);

  if (created + skipped === TEST_ACCOUNTS.length) {
    console.log('\n🎉 All test auth users are configured!');
    console.log('\n📧 Test Credentials:');
    console.log('   Password: TestPass123! (all accounts)');
    console.log('\n   Available accounts:');
    TEST_ACCOUNTS.forEach(acc => {
      console.log(`   - ${acc.email} (${acc.role})`);
    });
  }
}

createTestAuthUsers().catch(console.error);
